version: '3.8'
services:
  web:
    image: 'lizheming/waline'
    restart: always
    ports:
      - '8360:8360'
    environment:
      MYSQL_DB: 'waline'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_HOST: 'db'
      MYSQL_PORT: '3306'

  db:
    image: 'mysql:5.7'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'waline'